name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  orm: ^5.3.4
  json_annotation: ^4.9.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  dotenv: ^4.2.0
  crypto: ^3.0.6
  dart_jsonwebtoken: ^3.2.0
  collection: ^1.19.1
  logging: ^1.2.0
  http: ^1.2.1
  logger: ^2.0.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  lints: ^6.0.0
  test: ^1.26.2
